services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: inventario
      POSTGRES_USER: inventario_user
      POSTGRES_PASSWORD: inventario_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - app-net

  backend-app:
    build:
      context: ./backend
    container_name: backend-app
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/inventario
      SPRING_DATASOURCE_USERNAME: inventario_user
      SPRING_DATASOURCE_PASSWORD: inventario_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SERVER_PORT: "8080"
    ports:
      - "8082:8080"
    networks:
      - app-net

  frontend-app:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8082
    container_name: frontend-app
    ports:
      - "3000:80"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data:
